services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - vv-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vv-network

networks:
  vv-network:
    driver: bridge
