from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import io

def generate_pdf_report(prediction_result: dict, input_data: dict) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor("#2C3E50"),
        spaceAfter=12
    )
    
    section_style = ParagraphStyle(
        'SectionStyle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor("#2980B9"),
        spaceBefore=10,
        spaceAfter=6
    )
    
    elements = []
    
    # Title
    elements.append(Paragraph("Varicose Vein Recovery Prediction Report", title_style))
    elements.append(Spacer(1, 12))
    
    # Patient Information
    elements.append(Paragraph("Patient Inputs", section_style))
    patient_data = [
        ["Field", "Value"],
        ["Age", str(input_data.get("age"))],
        ["Gender", str(input_data.get("gender"))],
        ["BMI", str(input_data.get("bmi"))],
        ["Pain Level", f"{input_data.get('pain_level')}/10"],
        ["Swelling Level", f"{input_data.get('swelling_level')}/10"],
        ["Activity Level", f"{input_data.get('activity_level')}/10"],
        ["Beetroot Intake", str(input_data.get("beetroot_intake"))],
        ["Fenugreek Intake", str(input_data.get("fenugreek_intake"))]
    ]
    t1 = Table(patient_data, colWidths=[150, 200])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ]))
    elements.append(t1)
    
    # Prediction Results
    elements.append(Paragraph("Assessment Results", section_style))
    elements.append(Paragraph(f"<b>Risk Level:</b> {prediction_result['risk_level']} (Confidence: {prediction_result['risk_confidence']:.1%})", styles['Normal']))
    elements.append(Paragraph(f"<b>Estimated Recovery:</b> {prediction_result['recovery_weeks_mean']} weeks (Range: {prediction_result['recovery_weeks_min']}-{prediction_result['recovery_weeks_max']} weeks)", styles['Normal']))
    elements.append(Spacer(1, 12))
    
    # Scenario Comparison
    elements.append(Paragraph("Scenario Comparison", section_style))
    scenarios = prediction_result.get("scenarios", {})
    scenario_data = [["Scenario", "Risk Level", "Recovery Weeks"]]
    for name, data in scenarios.items():
        scenario_data.append([name.replace("_", " ").title(), data["risk"], str(data["recovery_weeks"])])
    
    t2 = Table(scenario_data, colWidths=[150, 100, 100])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ]))
    elements.append(t2)
    
    # SHAP Factors
    elements.append(Paragraph("Top 5 Impact Factors", section_style))
    shap_data = [["Feature", "Impact Value", "Type"]]
    for item in prediction_result.get("shap_values", []):
        shap_data.append([item["feature"], f"{item['value']:.4f}", item["impact"]])
        
    t3 = Table(shap_data, colWidths=[150, 100, 100])
    t3.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgreen),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    elements.append(t3)
    
    # Recommendations
    elements.append(Paragraph("Recommendations", section_style))
    for rec in prediction_result.get("recommendations", []):
        elements.append(Paragraph(f"• {rec}", styles['Normal']))
    
    # Disclaimer
    elements.append(Spacer(1, 24))
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.red)
    elements.append(Paragraph("DISCLAIMER: This report is generated by an AI model trained on synthetic data for educational/demo purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment.", disclaimer_style))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
